# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 422678c8a1c05c21c4a5c4f364c055e5d8ea05d2d66367e2f557a636c5ca452bbe1fc1a466cfd5e83a0b47cbbc72d32d73dc432fb5905532ac4907cf6f749ae7

test:
  secret_key_base: 68258047500af752bc773cdd92f1af2b2583fa7a333598c6240b6a997cac4126050b060e58f4948854d260794898926659f5cdd6a9c86c66e4a757949e74a6e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
